CREATE TABLE user (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  created TIMESTAMP,
  modified TIMESTAMP,
  last_login TIMESTAMP,
  token VARCHAR(512),
  is_active BOOLEAN
);

CREATE TABLE phone (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(36),
  number VARCHAR(50),
  citycode VARCHAR(20),
  contrycode VARCHAR(20),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id)
);
